### ISSUE TITLE
[Feature Request] Export to plaintext instead of .json

### ISSUE THREAD

**Issue by OKN1212** [lmg-anon/mikupad#28]
Since this is a novel-esque frontend I think it's only natural someone might want to export the main prompt box to plaintext format to upload it somewhere else for example. Though one can just copy and paste it to notepad I guess, so it's not really high priority.

**Comment by culturedniichan** [comment]
Currently it's dumping all of the storage. I see what you mean. Right now I'm trying to implement an instruction template system since I use that a lot, but I will give this a thought. I think it would be pretty useful. Also, to be able to export "lorebooks" or other info and import it individually, so you can transport it to other sessions / pads.

**Comment by culturedniichan** [comment]
I wonder what a good place to put this button at would be. I feel like some sort of new side menu that can be collapsed or expanded, maybe on the left, would be needed, but I'm not that familiar with UI development. For now I think a good place could be the settings menu

**Comment by OKN1212** [comment]
Sounds good to me!

**Comment by culturedniichan** [comment]
PR done for this feature

**Comment by lmg-anon** [comment]
@culturedniichan's PR merged in the commit https://github.com/lmg-anon/mikupad/commit/f5593d4cbcc7457253f23552b3292d63a22a6db2!
